package dto;
// Generated 15-09-2018 21:02:12 by Hibernate Tools 4.3.1



/**
 * AtencionId generated by hbm2java
 */
public class AtencionId  implements java.io.Serializable {


     private int idatencion;
     private int usuarioIdusuario;

    public AtencionId() {
    }

    public AtencionId(int idatencion, int usuarioIdusuario) {
       this.idatencion = idatencion;
       this.usuarioIdusuario = usuarioIdusuario;
    }
   
    public int getIdatencion() {
        return this.idatencion;
    }
    
    public void setIdatencion(int idatencion) {
        this.idatencion = idatencion;
    }
    public int getUsuarioIdusuario() {
        return this.usuarioIdusuario;
    }
    
    public void setUsuarioIdusuario(int usuarioIdusuario) {
        this.usuarioIdusuario = usuarioIdusuario;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof AtencionId) ) return false;
		 AtencionId castOther = ( AtencionId ) other; 
         
		 return (this.getIdatencion()==castOther.getIdatencion())
 && (this.getUsuarioIdusuario()==castOther.getUsuarioIdusuario());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getIdatencion();
         result = 37 * result + this.getUsuarioIdusuario();
         return result;
   }   


}


