package dto;
// Generated 15-09-2018 21:02:12 by Hibernate Tools 4.3.1


import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Atencion generated by hbm2java
 */
public class Atencion  implements java.io.Serializable {


     private AtencionId id;
     private Tiposala tiposala;
     private Usuario usuario;
     private int totalatencion;
     private byte faturada;
     private int propina;
     private Date fecha;
     private Set<Comanda> comandas = new HashSet<Comanda>(0);

    public Atencion() {
    }

	
    public Atencion(AtencionId id, Tiposala tiposala, Usuario usuario, int totalatencion, byte faturada, int propina, Date fecha) {
        this.id = id;
        this.tiposala = tiposala;
        this.usuario = usuario;
        this.totalatencion = totalatencion;
        this.faturada = faturada;
        this.propina = propina;
        this.fecha = fecha;
    }
    public Atencion(AtencionId id, Tiposala tiposala, Usuario usuario, int totalatencion, byte faturada, int propina, Date fecha, Set<Comanda> comandas) {
       this.id = id;
       this.tiposala = tiposala;
       this.usuario = usuario;
       this.totalatencion = totalatencion;
       this.faturada = faturada;
       this.propina = propina;
       this.fecha = fecha;
       this.comandas = comandas;
    }
   
    public AtencionId getId() {
        return this.id;
    }
    
    public void setId(AtencionId id) {
        this.id = id;
    }
    public Tiposala getTiposala() {
        return this.tiposala;
    }
    
    public void setTiposala(Tiposala tiposala) {
        this.tiposala = tiposala;
    }
    public Usuario getUsuario() {
        return this.usuario;
    }
    
    public void setUsuario(Usuario usuario) {
        this.usuario = usuario;
    }
    public int getTotalatencion() {
        return this.totalatencion;
    }
    
    public void setTotalatencion(int totalatencion) {
        this.totalatencion = totalatencion;
    }
    public byte getFaturada() {
        return this.faturada;
    }
    
    public void setFaturada(byte faturada) {
        this.faturada = faturada;
    }
    public int getPropina() {
        return this.propina;
    }
    
    public void setPropina(int propina) {
        this.propina = propina;
    }
    public Date getFecha() {
        return this.fecha;
    }
    
    public void setFecha(Date fecha) {
        this.fecha = fecha;
    }
    public Set<Comanda> getComandas() {
        return this.comandas;
    }
    
    public void setComandas(Set<Comanda> comandas) {
        this.comandas = comandas;
    }




}


