package dto;
// Generated 15-09-2018 18:43:32 by Hibernate Tools 4.3.1



/**
 * ComandaProductoId generated by hbm2java
 */
public class ComandaProductoId  implements java.io.Serializable {


     private int comandaIdcomanda;
     private int productoIdproducto;

    public ComandaProductoId() {
    }

    public ComandaProductoId(int comandaIdcomanda, int productoIdproducto) {
       this.comandaIdcomanda = comandaIdcomanda;
       this.productoIdproducto = productoIdproducto;
    }
   
    public int getComandaIdcomanda() {
        return this.comandaIdcomanda;
    }
    
    public void setComandaIdcomanda(int comandaIdcomanda) {
        this.comandaIdcomanda = comandaIdcomanda;
    }
    public int getProductoIdproducto() {
        return this.productoIdproducto;
    }
    
    public void setProductoIdproducto(int productoIdproducto) {
        this.productoIdproducto = productoIdproducto;
    }


   public boolean equals(Object other) {
         if ( (this == other ) ) return true;
		 if ( (other == null ) ) return false;
		 if ( !(other instanceof ComandaProductoId) ) return false;
		 ComandaProductoId castOther = ( ComandaProductoId ) other; 
         
		 return (this.getComandaIdcomanda()==castOther.getComandaIdcomanda())
 && (this.getProductoIdproducto()==castOther.getProductoIdproducto());
   }
   
   public int hashCode() {
         int result = 17;
         
         result = 37 * result + this.getComandaIdcomanda();
         result = 37 * result + this.getProductoIdproducto();
         return result;
   }   


}


