package dto;
// Generated 15-09-2018 18:22:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Comanda generated by hbm2java
 */
public class Comanda  implements java.io.Serializable {


     private int idcomanda;
     private Atencion atencion;
     private int totalcomanda;
     private Set<ComandaProducto> comandaProductos = new HashSet<ComandaProducto>(0);

    public Comanda() {
    }

	
    public Comanda(int idcomanda, Atencion atencion, int totalcomanda) {
        this.idcomanda = idcomanda;
        this.atencion = atencion;
        this.totalcomanda = totalcomanda;
    }
    public Comanda(int idcomanda, Atencion atencion, int totalcomanda, Set<ComandaProducto> comandaProductos) {
       this.idcomanda = idcomanda;
       this.atencion = atencion;
       this.totalcomanda = totalcomanda;
       this.comandaProductos = comandaProductos;
    }
   
    public int getIdcomanda() {
        return this.idcomanda;
    }
    
    public void setIdcomanda(int idcomanda) {
        this.idcomanda = idcomanda;
    }
    public Atencion getAtencion() {
        return this.atencion;
    }
    
    public void setAtencion(Atencion atencion) {
        this.atencion = atencion;
    }
    public int getTotalcomanda() {
        return this.totalcomanda;
    }
    
    public void setTotalcomanda(int totalcomanda) {
        this.totalcomanda = totalcomanda;
    }
    public Set<ComandaProducto> getComandaProductos() {
        return this.comandaProductos;
    }
    
    public void setComandaProductos(Set<ComandaProducto> comandaProductos) {
        this.comandaProductos = comandaProductos;
    }




}


