package dto;
// Generated 15-09-2018 21:02:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Producto generated by hbm2java
 */
public class Producto  implements java.io.Serializable {


     private Integer idproducto;
     private Tipoproducto tipoproducto;
     private String nombreProducto;
     private int precio;
     private int stock;
     private byte enVenta;
     private Set<ComandaProducto> comandaProductos = new HashSet<ComandaProducto>(0);

    public Producto() {
    }

	
    public Producto(Tipoproducto tipoproducto, String nombreProducto, int precio, int stock, byte enVenta) {
        this.tipoproducto = tipoproducto;
        this.nombreProducto = nombreProducto;
        this.precio = precio;
        this.stock = stock;
        this.enVenta = enVenta;
    }
    public Producto(Tipoproducto tipoproducto, String nombreProducto, int precio, int stock, byte enVenta, Set<ComandaProducto> comandaProductos) {
       this.tipoproducto = tipoproducto;
       this.nombreProducto = nombreProducto;
       this.precio = precio;
       this.stock = stock;
       this.enVenta = enVenta;
       this.comandaProductos = comandaProductos;
    }
   
    public Integer getIdproducto() {
        return this.idproducto;
    }
    
    public void setIdproducto(Integer idproducto) {
        this.idproducto = idproducto;
    }
    public Tipoproducto getTipoproducto() {
        return this.tipoproducto;
    }
    
    public void setTipoproducto(Tipoproducto tipoproducto) {
        this.tipoproducto = tipoproducto;
    }
    public String getNombreProducto() {
        return this.nombreProducto;
    }
    
    public void setNombreProducto(String nombreProducto) {
        this.nombreProducto = nombreProducto;
    }
    public int getPrecio() {
        return this.precio;
    }
    
    public void setPrecio(int precio) {
        this.precio = precio;
    }
    public int getStock() {
        return this.stock;
    }
    
    public void setStock(int stock) {
        this.stock = stock;
    }
    public byte getEnVenta() {
        return this.enVenta;
    }
    
    public void setEnVenta(byte enVenta) {
        this.enVenta = enVenta;
    }
    public Set<ComandaProducto> getComandaProductos() {
        return this.comandaProductos;
    }
    
    public void setComandaProductos(Set<ComandaProducto> comandaProductos) {
        this.comandaProductos = comandaProductos;
    }




}


