package dto;
// Generated 15-09-2018 18:43:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Subtipoproducto generated by hbm2java
 */
public class Subtipoproducto  implements java.io.Serializable {


     private Integer idsubTipoProducto;
     private Tipoproducto tipoproducto;
     private String descripcionsubTipo;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Subtipoproducto() {
    }

	
    public Subtipoproducto(Tipoproducto tipoproducto, String descripcionsubTipo) {
        this.tipoproducto = tipoproducto;
        this.descripcionsubTipo = descripcionsubTipo;
    }
    public Subtipoproducto(Tipoproducto tipoproducto, String descripcionsubTipo, Set<Producto> productos) {
       this.tipoproducto = tipoproducto;
       this.descripcionsubTipo = descripcionsubTipo;
       this.productos = productos;
    }
   
    public Integer getIdsubTipoProducto() {
        return this.idsubTipoProducto;
    }
    
    public void setIdsubTipoProducto(Integer idsubTipoProducto) {
        this.idsubTipoProducto = idsubTipoProducto;
    }
    public Tipoproducto getTipoproducto() {
        return this.tipoproducto;
    }
    
    public void setTipoproducto(Tipoproducto tipoproducto) {
        this.tipoproducto = tipoproducto;
    }
    public String getDescripcionsubTipo() {
        return this.descripcionsubTipo;
    }
    
    public void setDescripcionsubTipo(String descripcionsubTipo) {
        this.descripcionsubTipo = descripcionsubTipo;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


