package dto;
// Generated 15-09-2018 18:43:32 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipousuario generated by hbm2java
 */
public class Tipousuario  implements java.io.Serializable {


     private Integer idtipoUsuario;
     private String descripciontipoU;
     private Set<Usuario> usuarios = new HashSet<Usuario>(0);

    public Tipousuario() {
    }

	
    public Tipousuario(String descripciontipoU) {
        this.descripciontipoU = descripciontipoU;
    }
    public Tipousuario(String descripciontipoU, Set<Usuario> usuarios) {
       this.descripciontipoU = descripciontipoU;
       this.usuarios = usuarios;
    }
   
    public Integer getIdtipoUsuario() {
        return this.idtipoUsuario;
    }
    
    public void setIdtipoUsuario(Integer idtipoUsuario) {
        this.idtipoUsuario = idtipoUsuario;
    }
    public String getDescripciontipoU() {
        return this.descripciontipoU;
    }
    
    public void setDescripciontipoU(String descripciontipoU) {
        this.descripciontipoU = descripciontipoU;
    }
    public Set<Usuario> getUsuarios() {
        return this.usuarios;
    }
    
    public void setUsuarios(Set<Usuario> usuarios) {
        this.usuarios = usuarios;
    }




}


