package dto;
// Generated 15-09-2018 21:02:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoproducto generated by hbm2java
 */
public class Tipoproducto  implements java.io.Serializable {


     private Integer idtipoProducto;
     private String descripcionTipoP;
     private Set<Producto> productos = new HashSet<Producto>(0);

    public Tipoproducto() {
    }

	
    public Tipoproducto(String descripcionTipoP) {
        this.descripcionTipoP = descripcionTipoP;
    }
    public Tipoproducto(String descripcionTipoP, Set<Producto> productos) {
       this.descripcionTipoP = descripcionTipoP;
       this.productos = productos;
    }
   
    public Integer getIdtipoProducto() {
        return this.idtipoProducto;
    }
    
    public void setIdtipoProducto(Integer idtipoProducto) {
        this.idtipoProducto = idtipoProducto;
    }
    public String getDescripcionTipoP() {
        return this.descripcionTipoP;
    }
    
    public void setDescripcionTipoP(String descripcionTipoP) {
        this.descripcionTipoP = descripcionTipoP;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }




}


