package dto;
// Generated 15-09-2018 21:02:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tiposala generated by hbm2java
 */
public class Tiposala  implements java.io.Serializable {


     private Integer idtipoSala;
     private String desctipoSala;
     private Set<Atencion> atencions = new HashSet<Atencion>(0);

    public Tiposala() {
    }

	
    public Tiposala(String desctipoSala) {
        this.desctipoSala = desctipoSala;
    }
    public Tiposala(String desctipoSala, Set<Atencion> atencions) {
       this.desctipoSala = desctipoSala;
       this.atencions = atencions;
    }
   
    public Integer getIdtipoSala() {
        return this.idtipoSala;
    }
    
    public void setIdtipoSala(Integer idtipoSala) {
        this.idtipoSala = idtipoSala;
    }
    public String getDesctipoSala() {
        return this.desctipoSala;
    }
    
    public void setDesctipoSala(String desctipoSala) {
        this.desctipoSala = desctipoSala;
    }
    public Set<Atencion> getAtencions() {
        return this.atencions;
    }
    
    public void setAtencions(Set<Atencion> atencions) {
        this.atencions = atencions;
    }




}


