package dto;
// Generated 15-09-2018 18:22:47 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Tipoproducto generated by hbm2java
 */
public class Tipoproducto  implements java.io.Serializable {


     private int idtipoProducto;
     private String descripcionTipoP;
     private Set<Producto> productos = new HashSet<Producto>(0);
     private Set<Subtipoproducto> subtipoproductos = new HashSet<Subtipoproducto>(0);

    public Tipoproducto() {
    }

	
    public Tipoproducto(int idtipoProducto, String descripcionTipoP) {
        this.idtipoProducto = idtipoProducto;
        this.descripcionTipoP = descripcionTipoP;
    }
    public Tipoproducto(int idtipoProducto, String descripcionTipoP, Set<Producto> productos, Set<Subtipoproducto> subtipoproductos) {
       this.idtipoProducto = idtipoProducto;
       this.descripcionTipoP = descripcionTipoP;
       this.productos = productos;
       this.subtipoproductos = subtipoproductos;
    }
   
    public int getIdtipoProducto() {
        return this.idtipoProducto;
    }
    
    public void setIdtipoProducto(int idtipoProducto) {
        this.idtipoProducto = idtipoProducto;
    }
    public String getDescripcionTipoP() {
        return this.descripcionTipoP;
    }
    
    public void setDescripcionTipoP(String descripcionTipoP) {
        this.descripcionTipoP = descripcionTipoP;
    }
    public Set<Producto> getProductos() {
        return this.productos;
    }
    
    public void setProductos(Set<Producto> productos) {
        this.productos = productos;
    }
    public Set<Subtipoproducto> getSubtipoproductos() {
        return this.subtipoproductos;
    }
    
    public void setSubtipoproductos(Set<Subtipoproducto> subtipoproductos) {
        this.subtipoproductos = subtipoproductos;
    }




}


