package dto;
// Generated 15-09-2018 21:02:12 by Hibernate Tools 4.3.1


import java.util.HashSet;
import java.util.Set;

/**
 * Usuario generated by hbm2java
 */
public class Usuario  implements java.io.Serializable {


     private Integer idusuario;
     private Tipousuario tipousuario;
     private String nombreusuario;
     private String passusuario;
     private String cuentausuario;
     private byte activo;
     private Set<Atencion> atencions = new HashSet<Atencion>(0);

    public Usuario() {
    }

	
    public Usuario(Tipousuario tipousuario, String nombreusuario, String passusuario, String cuentausuario, byte activo) {
        this.tipousuario = tipousuario;
        this.nombreusuario = nombreusuario;
        this.passusuario = passusuario;
        this.cuentausuario = cuentausuario;
        this.activo = activo;
    }
    public Usuario(Tipousuario tipousuario, String nombreusuario, String passusuario, String cuentausuario, byte activo, Set<Atencion> atencions) {
       this.tipousuario = tipousuario;
       this.nombreusuario = nombreusuario;
       this.passusuario = passusuario;
       this.cuentausuario = cuentausuario;
       this.activo = activo;
       this.atencions = atencions;
    }
   
    public Integer getIdusuario() {
        return this.idusuario;
    }
    
    public void setIdusuario(Integer idusuario) {
        this.idusuario = idusuario;
    }
    public Tipousuario getTipousuario() {
        return this.tipousuario;
    }
    
    public void setTipousuario(Tipousuario tipousuario) {
        this.tipousuario = tipousuario;
    }
    public String getNombreusuario() {
        return this.nombreusuario;
    }
    
    public void setNombreusuario(String nombreusuario) {
        this.nombreusuario = nombreusuario;
    }
    public String getPassusuario() {
        return this.passusuario;
    }
    
    public void setPassusuario(String passusuario) {
        this.passusuario = passusuario;
    }
    public String getCuentausuario() {
        return this.cuentausuario;
    }
    
    public void setCuentausuario(String cuentausuario) {
        this.cuentausuario = cuentausuario;
    }
    public byte getActivo() {
        return this.activo;
    }
    
    public void setActivo(byte activo) {
        this.activo = activo;
    }
    public Set<Atencion> getAtencions() {
        return this.atencions;
    }
    
    public void setAtencions(Set<Atencion> atencions) {
        this.atencions = atencions;
    }




}


